env:
    global:
        - PACKAGE="GitSavvy"
        - SUBLIME_TEXT_VERSION="3"
        - UNITTESTING_TAG="master"

matrix:
    include:
        - name: Linux
          os: linux
          language: python
        - name: OSX
          os: osx
          language: generic

services:
  - xvfb

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    - git config --global user.email gitsavvy@gitsavvy.com
    - git config --global user.name GitSavvy

install:
    - sh travis.sh bootstrap
    - sh travis.sh install_package_control
    - pip3 install python-coveralls

script:
    - sh travis.sh run_tests --coverage
    - sh travis.sh run_syntax_tests

after_success:
    - coveralls

notifications:
    email: false
